name: Build BBTools

on:
  push:
    branches: [ master, main ]
    paths:
      - 'BBTools/current/**/*.java'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'BBTools/current/**/*.java'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Install Eclipse Compiler (ecj)
      run: |
        # Download Eclipse compiler
        wget https://download.eclipse.org/eclipse/downloads/drops4/R-4.29-202309031000/ecj-4.29.jar
        
    - name: Create output directories
      run: |
        cd BBTools
        mkdir -p compiled_classes
        
    - name: Compile BBTools with Eclipse Compiler
      run: |
        cd BBTools
        echo "Compiling BBTools with Eclipse Compiler..."
        echo "Using Java 17+ to run compiler, but targeting Java 7 bytecode..."
        
        # Find all Java files in all subdirectories
        find current -name "*.java" > source_files.txt
        
        # Count files
        FILE_COUNT=$(wc -l < source_files.txt)
        echo "Found $FILE_COUNT Java source files to compile"
        
        # Compile with ecj
        # - Run compiler with Java 21 (for incubator.vector and latest optimizations)
        # - Target Java 7 bytecode output (-7)
        # - Eclipse compiler is MUCH faster than javac for large projects
        # - NO -proceedOnError: we want to fail on actual errors!
        java --add-modules jdk.incubator.vector \
          -jar ../ecj-4.29.jar \
          -7 \
          -nowarn \
          -cp ".:current:current/*:current/*/*" \
          @source_files.txt \
          -d compiled_classes
          
        # Check exit code
        COMPILE_RESULT=$?
        if [ $COMPILE_RESULT -ne 0 ]; then
          echo "ERROR: Compilation failed with exit code $COMPILE_RESULT"
          echo "This is a real error that needs fixing!"
          exit 1
        fi
          
        # Check if compilation produced output
        if [ ! -d compiled_classes ] || [ -z "$(ls -A compiled_classes)" ]; then
          echo "ERROR: No class files were generated!"
          exit 1
        fi
          
    - name: Verify compilation
      run: |
        cd BBTools
        echo "Checking compiled classes..."
        CLASS_COUNT=$(find compiled_classes -name "*.class" | wc -l)
        echo "Compiled $CLASS_COUNT classes"
        
        if [ "$CLASS_COUNT" -lt 1000 ]; then
          echo "Warning: Expected more than 1000 classes, only found $CLASS_COUNT"
          exit 1
        fi
        
        echo "Compilation successful!"
        
    - name: Package compiled classes
      run: |
        cd BBTools
        # Copy class files to their proper locations
        echo "Copying class files to current/ directory structure..."
        cd compiled_classes
        find . -name "*.class" -exec cp --parents {} ../current/ \;
        cd ..
        
        # Create a release archive with compiled classes
        echo "Creating release archive..."
        tar -czf ../BBTools_compiled.tar.gz .
        
    - name: Upload compiled artifact
      uses: actions/upload-artifact@v4
      with:
        name: BBTools-compiled
        path: BBTools_compiled.tar.gz
        retention-days: 30
        
    - name: Upload class files
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: class-files
        path: BBTools/current/**/*.class
        retention-days: 90

  test-compilation:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download compiled artifact
      uses: actions/download-artifact@v4
      with:
        name: BBTools-compiled
        
    - name: Extract and test
      run: |
        tar -xzf BBTools_compiled.tar.gz
        
        # Make shell scripts executable
        chmod +x *.sh
        
        # Test that BBDuk runs
        echo "Testing BBDuk..."
        echo ">test" > test.fa
        echo "ACGTACGTACGT" >> test.fa
        
        ./bbduk.sh in=test.fa out=out.fa ktrim=r k=23 mink=11 hdist=1 tpe tbo 2>&1 | head -20
        
        if [ -f out.fa ]; then
          echo "BBDuk test successful!"
        else
          echo "BBDuk test failed!"
          exit 1
        fi